/lidar_processing:
  pointcloud_saver:
    ros__parameters:
      cloud_topic: "/luminar_points"
      filename_base: "points"
      file_extension: ".csv"
      parse_from_bag: False
      bagfile: "points.bag"
