/lidar_processing:
  grid_ground_processor:
    ros__parameters:
      input_cloud_topic: '/luminar_points'
      output_nonground_topic: '/lidar/nonground_points'

      grid_resolution: 0.5

      height_variance_threshold: 0.005
      min_height_threshold: 0.1
      min_points_threshold: 5

      x_min: -70.0
      x_max: 70.0
      y_min: -25.0
      y_max: 25.0
      z_min: -0.5
      z_max: 2.5

      ego_x_min: -3.0
      ego_x_max: 3.0
      ego_y_min: -2.0
      ego_y_max: 2.0
